// <auto-generated />
using System;
using DietPlanner.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DietPlanner.Api.Migrations
{
    [DbContext(typeof(DietPlannerContext))]
    [Migration("20190403165914_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DietPlanner.Core.Domain.CustomDay", b =>
                {
                    b.Property<Guid>("CustomDayId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Calories");

                    b.Property<DateTime>("Date");

                    b.Property<Guid>("PlanId");

                    b.HasKey("CustomDayId");

                    b.HasIndex("PlanId");

                    b.ToTable("CustomDay");
                });

            modelBuilder.Entity("DietPlanner.Core.Domain.Plan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlannedWeight");

                    b.Property<DateTime>("TargetDate");

                    b.Property<Guid>("UserId");

                    b.HasKey("PlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Plan");
                });

            modelBuilder.Entity("DietPlanner.Core.Domain.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DietPlanner.Core.Domain.CustomDay", b =>
                {
                    b.HasOne("DietPlanner.Core.Domain.Plan")
                        .WithMany("CustomDays")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DietPlanner.Core.Domain.Plan", b =>
                {
                    b.HasOne("DietPlanner.Core.Domain.User")
                        .WithOne("Plan")
                        .HasForeignKey("DietPlanner.Core.Domain.Plan", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
